# Generated by Django 3.2.6 on 2022-12-01 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(79999999999), django.core.validators.MinValueValidator(70000000000)])),
                ('operator_code', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('timezone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('filter', models.CharField(max_length=100)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_status', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('mailing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mailing')),
            ],
        ),
    ]
