# Generated by Django 3.2.6 on 2022-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='filter',
            field=models.CharField(default='', max_length=100),
        ),
    ]
