# Generated by Django 3.2.6 on 2022-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mailing_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='filter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
